server:
  port: 9004
spring:
  application:
    name: adm
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    org:
      hibernate:
        envers:
          default_schema: hist
          audit_table_suffix: _hist
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
